version: 2

project_name: tunetty

builds:
  - id: tunetty
    binary: tunetty
    main: ./cmd/tunetty
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .CommitDate }}

archives:
  - id: default
    ids:
      - tunetty
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

source:
  enabled: true

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot-{{ .ShortCommit }}'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^chore'
      - '^test'
      - '^ci'
      - '^build'
      - '^style'
      - '^Merge '
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactors
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Others
      order: 999

release:
  github:
    owner: jmnser
    name: tunetty
  draft: false
  prerelease: auto
  mode: replace
  name_template: 'v{{ .Version }}'
